print("What is your name, human?")
name = input()
print("How old are you, (in years)?")
age = int(input())
print("How tall are you (in meters)?")
hight = float(input())
print("How muc do you weight (in KG)?")
weight = float(input())
bmi = weight/(hight**2)
print(f"{name} + you are {age} years old. Your BMI is {bmi: .2f}")